{
  "dataType": "CVE_RECORD",
  "containers": {
    "adp": [
      {
        "title": "CISA ADP Vulnrichment",
        "metrics": [
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2024-37400",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "none"
                  },
                  {
                    "Automatable": "yes"
                  },
                  {
                    "Technical Impact": "partial"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-11-13T16:56:03.123820Z"
              }
            }
          }
        ],
        "affected": [
          {
            "cpes": [
              "cpe:2.3:a:ivanti:connect_secure:-:*:*:*:*:*:*:*"
            ],
            "vendor": "ivanti",
            "product": "connect_secure",
            "versions": [
              {
                "status": "affected",
                "version": "22.7R2.3"
              }
            ],
            "defaultStatus": "unaffected"
          }
        ],
        "problemTypes": [
          {
            "descriptions": [
              {
                "lang": "en",
                "type": "CWE",
                "cweId": "CWE-125",
                "description": "CWE-125 Out-of-bounds Read"
              }
            ]
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-11-13T16:57:11.624Z"
        }
      }
    ],
    "cna": {
      "metrics": [
        {
          "cvssV3_0": {
            "version": "3.0",
            "baseScore": 7.5,
            "baseSeverity": "HIGH",
            "vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
          }
        }
      ],
      "affected": [
        {
          "vendor": "Ivanti",
          "product": "Connect Secure",
          "versions": [
            {
              "status": "affected",
              "version": "22.7R2.3",
              "lessThan": "22.7R2.3",
              "versionType": "custom"
            }
          ],
          "defaultStatus": "unaffected"
        }
      ],
      "references": [
        {
          "url": "https://forums.ivanti.com/s/article/Security-Advisory-Ivanti-Connect-Secure-ICS-Ivanti-Policy-Secure-IPS-Ivanti-Secure-Access-Client-ISAC-Multiple-CVEs"
        }
      ],
      "descriptions": [
        {
          "lang": "en",
          "value": "An out of bounds read in Ivanti Connect Secure before version 22.7R2.3 allows a remote unauthenticated attacker to trigger an infinite loop, causing a denial of service."
        }
      ],
      "providerMetadata": {
        "orgId": "36234546-b8fa-4601-9d6f-f4e334aa8ea1",
        "shortName": "hackerone",
        "dateUpdated": "2024-11-13T01:54:45.506Z"
      }
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2024-37400",
    "state": "PUBLISHED",
    "dateUpdated": "2024-11-13T16:57:19.557Z",
    "dateReserved": "2024-06-08T01:04:07.093Z",
    "assignerOrgId": "36234546-b8fa-4601-9d6f-f4e334aa8ea1",
    "datePublished": "2024-11-13T01:54:45.506Z",
    "assignerShortName": "hackerone"
  },
  "dataVersion": "5.1"
}