{
  "dataType": "CVE_RECORD",
  "containers": {
    "adp": [
      {
        "title": "CVE Program Container",
        "references": [
          {
            "url": "https://jira.mongodb.org/browse/SERVER-38275",
            "tags": [
              "x_refsource_MISC",
              "x_transferred"
            ]
          }
        ],
        "providerMetadata": {
          "orgId": "af854a3a-2127-422b-91ae-364da2661108",
          "shortName": "CVE",
          "dateUpdated": "2024-08-05T12:26:39.551Z"
        }
      },
      {
        "title": "CISA ADP Vulnrichment",
        "metrics": [
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2018-25004",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "none"
                  },
                  {
                    "Automatable": "no"
                  },
                  {
                    "Technical Impact": "partial"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-01-26T18:55:11.972039Z"
              }
            }
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-11-19T15:42:49.750Z"
        }
      }
    ],
    "cna": {
      "title": "Invariant failure when explaining a find with a UUID",
      "source": {
        "discovery": "INTERNAL"
      },
      "metrics": [
        {
          "format": "CVSS",
          "cvssV3_1": {
            "scope": "UNCHANGED",
            "version": "3.1",
            "baseScore": 4.9,
            "attackVector": "NETWORK",
            "baseSeverity": "MEDIUM",
            "vectorString": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:N/I:N/A:H",
            "temporalScore": 4.8,
            "integrityImpact": "NONE",
            "userInteraction": "NONE",
            "attackComplexity": "LOW",
            "remediationLevel": "UNAVAILABLE",
            "reportConfidence": "CONFIRMED",
            "temporalSeverity": "MEDIUM",
            "availabilityImpact": "HIGH",
            "privilegesRequired": "HIGH",
            "exploitCodeMaturity": "FUNCTIONAL",
            "confidentialityImpact": "NONE"
          },
          "scenarios": [
            {
              "lang": "en",
              "value": "GENERAL"
            }
          ]
        }
      ],
      "affected": [
        {
          "vendor": "MongoDB Inc.",
          "product": "MongoDB Server",
          "versions": [
            {
              "status": "affected",
              "version": "3.6",
              "lessThan": "3.6.11",
              "versionType": "custom"
            },
            {
              "status": "affected",
              "version": "4.0",
              "lessThan": "4.0.6",
              "versionType": "custom"
            }
          ],
          "defaultStatus": "unaffected"
        }
      ],
      "datePublic": "2021-02-26T00:00:00.000Z",
      "references": [
        {
          "url": "https://jira.mongodb.org/browse/SERVER-38275",
          "tags": [
            "x_refsource_MISC"
          ]
        }
      ],
      "x_generator": {
        "engine": "Vulnogram 0.0.9"
      },
      "descriptions": [
        {
          "lang": "en",
          "value": "A user authorized to performing a specific type of query may trigger a denial of service by issuing a generic explain command on a find query. This issue affects MongoDB Server v4.0 versions prior to 4.0.6 and MongoDB Server v3.6 versions prior to 3.6.11.",
          "supportingMedia": [
            {
              "type": "text/html",
              "value": "<p>A user authorized to performing a specific type of query may trigger a denial of service by issuing a generic explain command on a find query. This issue affects MongoDB Server v4.0 versions prior to 4.0.6 and MongoDB Server v3.6 versions prior to 3.6.11.</p>",
              "base64": false
            }
          ]
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "lang": "en",
              "type": "CWE",
              "cweId": "CWE-20",
              "description": "CWE-20 Improper Input Validation"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "a39b4221-9bd0-4244-95fc-f3e2e07f1deb",
        "shortName": "mongodb",
        "dateUpdated": "2024-01-23T14:30:20.718Z"
      },
      "x_legacyV4Record": {
        "impact": {
          "cvss": {
            "scope": "UNCHANGED",
            "version": "3.1",
            "baseScore": 4.8,
            "attackVector": "NETWORK",
            "baseSeverity": "MEDIUM",
            "vectorString": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:N/I:N/A:H/E:F/RL:U/RC:C",
            "integrityImpact": "NONE",
            "userInteraction": "NONE",
            "attackComplexity": "LOW",
            "availabilityImpact": "HIGH",
            "privilegesRequired": "HIGH",
            "confidentialityImpact": "NONE"
          }
        },
        "source": {
          "discovery": "INTERNAL"
        },
        "affects": {
          "vendor": {
            "vendor_data": [
              {
                "product": {
                  "product_data": [
                    {
                      "version": {
                        "version_data": [
                          {
                            "version_name": "3.6",
                            "version_value": "3.6.11",
                            "version_affected": "<"
                          },
                          {
                            "version_name": "4.0",
                            "version_value": "4.0.6",
                            "version_affected": "<"
                          }
                        ]
                      },
                      "product_name": "MongoDB Server"
                    }
                  ]
                },
                "vendor_name": "MongoDB Inc."
              }
            ]
          }
        },
        "data_type": "CVE",
        "generator": {
          "engine": "Vulnogram 0.0.9"
        },
        "references": {
          "reference_data": [
            {
              "url": "https://jira.mongodb.org/browse/SERVER-38275",
              "name": "https://jira.mongodb.org/browse/SERVER-38275",
              "refsource": "MISC"
            }
          ]
        },
        "data_format": "MITRE",
        "description": {
          "description_data": [
            {
              "lang": "eng",
              "value": "A user authorized to performing a specific type of query may trigger a denial of service by issuing a generic explain command on a find query. This issue affects: MongoDB Inc. MongoDB Server v4.0 versions prior to 4.0.6; MongoDB Server v3.6 versions prior to 3.6.11."
            }
          ]
        },
        "problemtype": {
          "problemtype_data": [
            {
              "description": [
                {
                  "lang": "eng",
                  "value": "CWE-20 Improper Input Validation"
                }
              ]
            }
          ]
        },
        "data_version": "4.0",
        "CVE_data_meta": {
          "ID": "CVE-2018-25004",
          "STATE": "PUBLIC",
          "TITLE": "Invariant failure when explaining a find with a UUID",
          "ASSIGNER": "cna@mongodb.com",
          "DATE_PUBLIC": "2021-02-26T17:00:00.000Z"
        }
      }
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2018-25004",
    "state": "PUBLISHED",
    "dateUpdated": "2024-11-19T15:42:57.505Z",
    "dateReserved": "2021-01-29T00:00:00",
    "assignerOrgId": "a39b4221-9bd0-4244-95fc-f3e2e07f1deb",
    "datePublished": "2021-03-01T16:15:14.484681Z",
    "assignerShortName": "mongodb"
  },
  "dataVersion": "5.1"
}