{
  "dataType": "CVE_RECORD",
  "containers": {
    "adp": [
      {
        "title": "CVE Program Container",
        "references": [
          {
            "url": "https://github.com/vinitkumar/json2xml/issues/106",
            "tags": [
              "x_transferred"
            ]
          },
          {
            "url": "https://github.com/vinitkumar/json2xml/pull/107",
            "tags": [
              "x_transferred"
            ]
          },
          {
            "url": "https://github.com/vinitkumar/json2xml/pull/107/files",
            "tags": [
              "x_transferred"
            ]
          },
          {
            "url": "https://packaging.python.org/en/latest/guides/analyzing-pypi-package-downloads/",
            "tags": [
              "x_transferred"
            ]
          }
        ],
        "providerMetadata": {
          "orgId": "af854a3a-2127-422b-91ae-364da2661108",
          "shortName": "CVE",
          "dateUpdated": "2024-08-03T04:29:01.543Z"
        }
      },
      {
        "title": "CISA ADP Vulnrichment",
        "metrics": [
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2022-25024",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "poc"
                  },
                  {
                    "Automatable": "yes"
                  },
                  {
                    "Technical Impact": "partial"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-10-03T17:46:20.740240Z"
              }
            }
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-10-03T17:46:34.667Z"
        }
      }
    ],
    "cna": {
      "affected": [
        {
          "vendor": "n/a",
          "product": "n/a",
          "versions": [
            {
              "status": "affected",
              "version": "n/a"
            }
          ]
        }
      ],
      "references": [
        {
          "url": "https://github.com/vinitkumar/json2xml/issues/106"
        },
        {
          "url": "https://github.com/vinitkumar/json2xml/pull/107"
        },
        {
          "url": "https://github.com/vinitkumar/json2xml/pull/107/files"
        },
        {
          "url": "https://packaging.python.org/en/latest/guides/analyzing-pypi-package-downloads/"
        }
      ],
      "descriptions": [
        {
          "lang": "en",
          "value": "The json2xml package through 3.12.0 for Python allows an error in typecode decoding enabling a remote attack that can lead to an exception, causing a denial of service."
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "lang": "en",
              "type": "text",
              "description": "n/a"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "shortName": "mitre",
        "dateUpdated": "2023-08-22T15:44:27.629929"
      }
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2022-25024",
    "state": "PUBLISHED",
    "dateUpdated": "2024-10-03T17:46:39.654Z",
    "dateReserved": "2022-02-14T00:00:00",
    "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
    "datePublished": "2023-08-22T00:00:00",
    "assignerShortName": "mitre"
  },
  "dataVersion": "5.1"
}