{
  "dataType": "CVE_RECORD",
  "containers": {
    "adp": [
      {
        "title": "CISA ADP Vulnrichment",
        "metrics": [
          {
            "cvssV3_1": {
              "scope": "UNCHANGED",
              "version": "3.1",
              "baseScore": 7.5,
              "attackVector": "NETWORK",
              "baseSeverity": "HIGH",
              "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "integrityImpact": "NONE",
              "userInteraction": "NONE",
              "attackComplexity": "LOW",
              "availabilityImpact": "HIGH",
              "privilegesRequired": "NONE",
              "confidentialityImpact": "NONE"
            }
          },
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2024-53432",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "poc"
                  },
                  {
                    "Automatable": "yes"
                  },
                  {
                    "Technical Impact": "partial"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-12-04T14:35:56.398088Z"
              }
            }
          }
        ],
        "affected": [
          {
            "cpes": [
              "cpe:2.3:a:point_cloud_library:pcl:1.14.1:*:*:*:*:*:*:*"
            ],
            "vendor": "point_cloud_library",
            "product": "pcl",
            "versions": [
              {
                "status": "affected",
                "version": "1.14.1"
              }
            ],
            "defaultStatus": "unknown"
          }
        ],
        "problemTypes": [
          {
            "descriptions": [
              {
                "lang": "en",
                "type": "CWE",
                "cweId": "CWE-754",
                "description": "CWE-754 Improper Check for Unusual or Exceptional Conditions"
              }
            ]
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-12-04T15:36:35.274Z"
        }
      }
    ],
    "cna": {
      "affected": [
        {
          "vendor": "n/a",
          "product": "n/a",
          "versions": [
            {
              "status": "affected",
              "version": "n/a"
            }
          ]
        }
      ],
      "references": [
        {
          "url": "https://github.com/PointCloudLibrary/pcl/issues/6162"
        }
      ],
      "descriptions": [
        {
          "lang": "en",
          "value": "While parsing certain malformed PLY files, PCL version 1.14.1 crashes due to an uncaught std::out_of_range exception in PCLPointCloud2::at. This issue could potentially be exploited to cause a denial-of-service (DoS) attack when processing untrusted PLY files."
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "lang": "en",
              "type": "text",
              "description": "n/a"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "shortName": "mitre",
        "dateUpdated": "2024-11-21T17:24:10.543693"
      }
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2024-53432",
    "state": "PUBLISHED",
    "dateUpdated": "2024-12-04T15:36:47.876Z",
    "dateReserved": "2024-11-20T00:00:00",
    "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
    "datePublished": "2024-11-21T00:00:00",
    "assignerShortName": "mitre"
  },
  "dataVersion": "5.1"
}